### ISSUE TITLE
Unhandled ValueError in current_time

### ISSUE THREAD

**Issue by mweinelt** [cgtobi/PyRMVtransport#25]
Could probably be handled more gracefully.

```pytb
Traceback (most recent call last):
  File "/nix/store/az00yxlp4vylfy9ly9g5kmw23da3q3ib-python3.8-PyRMVtransport-0.2.10/lib/python3.8/site-packages/RMVtransport/rmvtransport.py", line 107, in get_departures
    self.now = self.current_time()
  File "/nix/store/az00yxlp4vylfy9ly9g5kmw23da3q3ib-python3.8-PyRMVtransport-0.2.10/lib/python3.8/site-packages/RMVtransport/rmvtransport.py", line 208, in current_time
    _date = datetime.strptime(self.obj.SBRes.SBReq.StartT.get("date"), "%Y%m%d")
  File "/nix/store/3v08lxfp10y5k5sk4302y0h3r9qg91fi-python3-3.8.6/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/nix/store/3v08lxfp10y5k5sk4302y0h3r9qg91fi-python3-3.8.6/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y%m%d'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/nix/store/ylafipqj1yhdssy9qvw8mwi3782gd076-homeassistant-2020.12.1/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/nix/store/ylafipqj1yhdssy9qvw8mwi3782gd076-homeassistant-2020.12.1/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/nix/store/ylafipqj1yhdssy9qvw8mwi3782gd076-homeassistant-2020.12.1/lib/python3.8/site-packages/homeassistant/components/rmvtransport/sensor.py", line 179, in async_update
    await self.data.async_update()
  File "/nix/store/ylafipqj1yhdssy9qvw8mwi3782gd076-homeassistant-2020.12.1/lib/python3.8/site-packages/homeassistant/components/rmvtransport/sensor.py", line 226, in async_update
    _data = await self.rmv.get_departures(
  File "/nix/store/az00yxlp4vylfy9ly9g5kmw23da3q3ib-python3.8-PyRMVtransport-0.2.10/lib/python3.8/site-packages/RMVtransport/rmvtransport.py", line 114, in get_departures
    raise RMVtransportError()
RMVtransport.errors.RMVtransportError
```

**Comment by cgtobi** [comment]
Sorry for the long wait. I've addressed this and leave the fix running for a day or two before shipping a new version. Thanks for reporting.
